version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: oqi
      POSTGRES_PASSWORD: oqi
      POSTGRES_DB: oqi_dev
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        DATABASE_URL: "postgresql://oqi:oqi@db:5432/oqi_dev"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://oqi:oqi@db:5432/oqi_dev?schema=public
      JWT_SECRET: your_secret_here
      COOKIE_NAME: oqi_session
      PORT: 8080
      FRONTEND_URL: http://localhost:3000
      DISABLE_SECURE_COOKIE: "true" 
      DISABLE_COOKIE_DOMAIN: "true"
      NODE_ENV: development
    ports:
      - "8080:8080"
  init:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        DATABASE_URL: "postgresql://oqi:oqi@db:5432/oqi_dev"
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma db push --schema=./prisma/schema.prisma &&
        npm run seed
      "
    environment:
      DATABASE_URL: postgresql://oqi:oqi@db:5432/oqi_dev

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api


volumes:
  dbdata:
